### ISSUE TITLE
Create LA Metro Rail pattern

### ISSUE THREAD

**Issue by matikin9** [maptimeLA/craftmap_adventure#11]
Create LA Metro Rail map pattern.
- Create printable colored pattern (embroidery & cross stitch).
- Identify matching DMC thread colors.

**Comment by techlady** [comment]
I like the idea of having the same stitch but a different color for the metro rail system. I think this would communicate what they are without explanation to most people. Also, if regular rail lines were black, but the metro lines used each line's real color, that would be useful. The colors now are red (Red Line), blue (Blue Line), light blue (Expo Line), gold (the Gold Line), purple (Wilshire Blvd. Line), green (Green Line), Orange (Orange busway), silver (Silver busway) and unknown (Crenshaw Line). We could make the Crenshaw line pink or magenta (there are no other warm colors in the South Bay area).

**Comment by JRHutson** [comment]
I like where Charlotte is going with this for the current lines. Should we include future lines? Has anyone else seen something about a shift to numbers rather than colors? I thought I saw something about a future shift since easily distinguishable colors are running out.

**Comment by JRHutson** [comment]
It looks like letters according to this. https://en.m.wikipedia.org/wiki/File:Future_Los_Angeles_County_Metro_Rail.svg

**Comment by techlady** [comment]
I was thinking that we should include lines that definitely are under construction, such as the Crenshaw Line, the Purple Line (Wilshire Blvd.) and the "regional connector." They are slated to open in the next couple of years. There is a map at http://theplan.metro.net/ of future plans, but it doesn't give specific dates. The whole plan supposedly will be finished by 2040.
I haven't found anything official yet that says that names will change to letters. (The reporter in me wants something from Metro saying that.)

**Comment by techlady** [comment]
I did find a PDF from 2015 about the renaming proposal, but nothing newer: http://media.metro.net/board/Items/2015/04_april/20150408wesitem5.pdf. This also is a map of the "current" system, which includes the Crenshaw Line.

**Comment by matikin9** [comment]
I like the idea of color coding, but the colors will be shifting with the completion of the Regional Connector.  We could have the rail be a base color (black) and then add in the line color using a whipped/laced/threaded stitch technique like this one: http://www.embroidery.rocksea.org/stitch/running-stitch/whipped-running-stitch/.  The nice thing about this is that it would be easy to replace if we wanted to update the map in the future for these changes.

Or, we could not worry about future changes and just consider this project a snapshot of the LA region at this point in time?

**Comment by colombene** [comment]
I think it would be much more manageable as a snapshot, without future lines. They can always be added. I couldn't find any news on the renaming/recolor project but I'd think that would have some notice if it were to roll out - all stations and info materials would have to change. Otherwise I think the next change is the Crenshaw line which opens 2 or 3 years from now.

**Comment by matikin9** [comment]
@colombene I recall with the Regional Connector, they were going to reconfigure some of the lines so that the Expo Line would be connected to one part of the Gold Line and the Blue line connected to another part.  I agree, it would be more manageable to do as a snapshot.  Then if we do colors representing the lines, I think the stitches should be distinctive enough that it's still obviously a rail line.

**Comment by techlady** [comment]
I like the whipped running stitch idea, and I'm not against the idea of doing a snapshot. However, I think we include lines already under construction.

**Comment by matikin9** [comment]
Tabling this for now.  While I think this could be a great independent map stitching project, for the purposes of the quilt it'll be easier to start with a single color.

**Comment by matikin9** [comment]
Just to note for the record, I think it would be really cool to have a stitched map that gets updated when they re-route the rail lines.  So like stitch it now with the current rail map, and then when the new one comes out, overlay it with the new lines to show how they've changed over time... so basically a 4-dimensional map since it shows the passage of time?!
